### ISSUE TITLE
permessage-deflate compression not working

### ISSUE THREAD

**Issue by richytong** [python-websockets/websockets#1637]
Hello, when I initiate the handshake from my WebSocket client [presidium-websocket](https://github.com/richytong/presidium-websocket) I send this message with the `permessage-deflate` extension header:

```
GET / HTTP/1.1
Host: localhost:7357
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: DSIhUE/XTvIxAia/1SfpgA==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

Then, I receive this response from python-websockets which indicates permessage-deflate is supported and going to be used:

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: n/K7yPleVJcb50uPAc77xCd6DCU=
Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12; client_max_window
_bits=12
Date: Mon, 07 Jul 2025 17:34:42 GMT
Server: Python/3.9 websockets/11.0.3
```

However, when I go to actually send a compressed message with permessage-deflate enabled (rsv1 is set), my client connection is closed immediately and I find this error in my python-websockets server:

```
connection handler failed
Traceback (most recent call last):
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 1084, in read_message
    frame = await self.read_data_frame(max_size=max_size)
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/framing.py", line 109, in read
    new_frame.check()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/frames
.py", line 320, in check
    raise exceptions.ProtocolError("reserved bits must be 0")
websockets.exceptions.ProtocolError: reserved bits must be 0
```

The first reserved bit (rsv1) should be set to 1 in this case. For now I will force my client websocket to not use compression with permessage-deflate to be able to keep communicating with my python webserver using the WebSocket protocol.

**Comment by richytong** [comment]
I sent this payload to the python-websockets server: https://gist.github.com/richytong/cb212c65704325d6fbd47137883269bf

**Comment by richytong** [comment]
Found the bug in my own implementation.

**Comment by aaugustin** [comment]
This is unexpected. This part of websockets is quite battle-tested.

Could you [enable debug logs](https://websockets.readthedocs.io/en/stable/howto/debugging.html) so we can see what websockets receives on the wire exactly, please?

**Comment by richytong** [comment]
Added logs printing `data` and `new_frame`, also `fin` and `rsv1`

```
2025-07-09 08:06:58,668 Using selector: EpollSelector
2025-07-09 08:06:58,668 server listening on 0.0.0.0:7357
Websocket server listening on port 7357
2025-07-09 08:07:10,943 = connection is CONNECTING
2025-07-09 08:07:10,944 < GET / HTTP/1.1
2025-07-09 08:07:10,944 < Host: localhost:7357
2025-07-09 08:07:10,944 < Upgrade: websocket
2025-07-09 08:07:10,945 < Connection: Upgrade
2025-07-09 08:07:10,945 < Sec-WebSocket-Key: UaiWB64CAa8NpWgfdCJqiA==
2025-07-09 08:07:10,945 < Sec-WebSocket-Version: 13
2025-07-09 08:07:10,945 < Sec-WebSocket-Extensions: permessage-deflate; client_max_window_
bits
2025-07-09 08:07:10,946 > HTTP/1.1 101 Switching Protocols
2025-07-09 08:07:10,946 > Upgrade: websocket
2025-07-09 08:07:10,946 > Connection: Upgrade
2025-07-09 08:07:10,946 > Sec-WebSocket-Accept: kz42aMJoWj64CsZwM6JsbRGNbN0=
2025-07-09 08:07:10,946 > Sec-WebSocket-Extensions: permessage-deflate; server_max_window_
bits=12; client_max_window_bits=12
2025-07-09 08:07:10,946 > Date: Wed, 09 Jul 2025 15:07:10 GMT
2025-07-09 08:07:10,946 > Server: Python/3.9 websockets/11.0.3
2025-07-09 08:07:10,946 connection open
2025-07-09 08:07:10,946 = connection is OPEN
data b'\x89\x80'
fin True
rsv1 False
new_frame PING '' [0 bytes]
extension new_frame PING '' [0 bytes]
2025-07-09 08:07:10,948 < PING '' [0 bytes]
2025-07-09 08:07:10,948 > PONG '' [0 bytes]
data b'A\xfe'
fin False
rsv1 True
2025-07-09 08:07:10,951 ! failing connection with code 1007
2025-07-09 08:07:10,952 = connection is CLOSING
2025-07-09 08:07:10,952 > CLOSE 1007 (invalid data) [2 bytes]
2025-07-09 08:07:10,952 x half-closing TCP connection
2025-07-09 08:07:10,953 = connection is CLOSED
2025-07-09 08:07:10,953 connection handler failed
Traceback (most recent call last):
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/framing.py", line 107, in read
    print('new_frame', new_frame)
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/frames.py", line 140, in __str__
    data = repr(self.data.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 0: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/home/richard/code/websockets/tmp.py", line 12, in echo
    async for message in websocket:
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 497, in __aiter__
    yield await self.recv()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1007 (invalid data); no close frame received
2025-07-09 08:07:10,956 connection closed
```

**Comment by richytong** [comment]
Here are the logs printing `data`, `new_frame`, and `new_frame` when it is decompressed

```
Websocket server listening on port 7357
2025-07-09 09:30:58,798 = connection is CONNECTING
2025-07-09 09:30:58,800 < GET / HTTP/1.1
2025-07-09 09:30:58,800 < Host: localhost:7357
2025-07-09 09:30:58,800 < Upgrade: websocket
2025-07-09 09:30:58,801 < Connection: Upgrade
2025-07-09 09:30:58,801 < Sec-WebSocket-Key: I8EsgIA7iOizMvUBDMDaPg==
2025-07-09 09:30:58,801 < Sec-WebSocket-Version: 13
2025-07-09 09:30:58,801 < Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
2025-07-09 09:30:58,802 > HTTP/1.1 101 Switching Protocols
2025-07-09 09:30:58,802 > Upgrade: websocket
2025-07-09 09:30:58,802 > Connection: Upgrade
2025-07-09 09:30:58,802 > Sec-WebSocket-Accept: nvtqfyWf+/oR6dKVJyS4mEG5pho=
2025-07-09 09:30:58,802 > Sec-WebSocket-Extensions: permessage-deflate; server_max_window_
bits=12; client_max_window_bits=12
2025-07-09 09:30:58,802 > Date: Wed, 09 Jul 2025 16:30:58 GMT
2025-07-09 09:30:58,802 > Server: Python/3.9 websockets/11.0.3
2025-07-09 09:30:58,802 connection open
2025-07-09 09:30:58,802 = connection is OPEN
data b'\x89\x80'
new_frame Frame(opcode=<Opcode.PING: 9>, data=b'', fin=True, rsv1=False, rsv2=False, rsv3=False)
new_frame extension Frame(opcode=<Opcode.PING: 9>, data=b'', fin=True, rsv1=False, rsv2=False, rsv3=False)
2025-07-09 09:30:58,804 < PING '' [0 bytes]
2025-07-09 09:30:58,804 > PONG '' [0 bytes]
data b'A\xfe'
new_frame Frame(opcode=<Opcode.TEXT: 1>, data=b'\xddVQ\x93\xa3\xac\xb6\xfd/\xf3\xcaW\x85\x
88\x88\xdc\xaa\xf30=\x1d\x93\xc9\xa4\x8d\x93\x18%\x9e:uKD:m\x90\xd8\x11\x89\xed\xf9\xf3\xb
7\x92\x9e\x99\xef<\xdc\xfb\x07.UR[\xd8({\xb3\xd6^\xfc\xfbK]i\xfd\xdf\xc3\x9b\xfc\xf2_\xff\
xfc\xf2\xedk\xb6\xd8g_\xfe\xfae\xf8_\xfe\xf5\xd7\x97\xa1y\xed\x1ac\xef\xd3\xf0\xffc\xbb\xf
d\xe3\x1f_\xfe\xf5\xd7?\xbf4\xddI\x15H\xe7y\x9c\x17E<\xa9\xb2@\x94\x02|\r\x01\xfc\x80\xc6a
\xba\xdd\x08/\x82{\x94\xb4\x92\xa8\x93_!V\x17\xba\xe79\x9a.jt:h\xc4\x18A\x86+\x7fr\x02?9\x
b1\x94\x9dX\xcd~\x08\xe6\x8e\x00w\t]L\x85?\xf5e\x91\x9c\x8eE\xd2U\x98\x036^\x15\xb6XbKO\xa
4\xd9h\x02\xae\xb3*X_\x16\xb1\xe2\xdd\x93\xe29\xaas\x94\x14|\x99\x0c\r\x80\'\x9c\xb4\xfb9\
x82;\xcf\xb6\'\xcaO\xa6\xccY\xc35\x11\x85\xee\x05\x8f\xd9\xb9\x82\xd7\xf7\x80a\x8e\x92\xd5
v\x1e\xe0\x1e\xdd\x83\xfb\xeb\x0b\x066\x04\xaaBD\xe4\xaf\x8f\x81<.\x8f\x05b\xa6\xc6\xd4\x8
b\xb6\xf3%\x04\xd7\x0bMS\xd0\xf0\x19B\xb8y\'\xcd\xb3\xc4\x12\xf6\xcc\xec\xbac\xf7t:\xfa\xe
bN\x14\xe4\xa31\x98U\x83\x92\xd5\xa0\xcf\xb2U\xfa<T\xad\xaaZ\xa9\xab\xe1\xfe\xd6VZ\xb5C\xa
5\xcf\xaa\x1d\xf4c@\xe9s\xf5\xe8\x86V\x0f\xd5\xdf+\xd4Y\x0f\xbf\xdf\xfe\xbaA\xc5g\x90Z\x06
\xa1\xc3t4\x97\x10@\x8f\xe1)\xa8\x0b\xf6Q\xe3\xf5(\xba\xbe\xaf\x96\xfa],\xc9\xad\xe6e\x04\
xb7\xf0J\xc6\x95\xc2\xe0\xf95\xd8n\xde\xc8\xf6:\x82\xd5N\xf3\xd8\x96\xb9>U\xbc\x88{q\x0f\x
ad\x99\rI\xa0\xc4\x12\xd78\xa1\xa7`l\x07\xc6\xa7\xe1\x88\x88\xe4\xf1\xd4\x94\xcbi\x14\xddt
\xad:4\xab\x91*\x9f\xb5\xb9\xc7\xd2\xc2\x97N\x12\x95\xf8\xe5g\xfax\\\xee\x0fz]\x14\x1a\xb5
b\xb5\x8e\xd8H{\x026o\xa4\xc1\x1f\x00OT\xa5\xf3\x14\x82\xf3\x99\x00L\xeaB*\x8eP\xcd\xfd\xd
d\xbb01\x88\x005\xa4\xe1}\xa4V\xee\x81\xa6\xad\xea\xc88#\xd5\x11Sv\xfa*\n\xe6\xd7\x1d\xb9\
x96\x9d\xbeT\x9d\xbe\x94\x9d\x9e*\xdd\xaa\xffl\x9fi\xfa\x95\xc9\x87)\xef\xfd\xa7\xf9\xdb\x
90\xad\xaa\xf4y\xf8\xdb\xef\xb7\xf3Y\x0ew\'\ra:\x10\x06%N\x1e\xc9Pd\xc47\xe8\x13\xcd\xf5$\
x8a\xdcJ\xee\'\x9d\xe0\x19\x8c\xe0s\x1f<\xfc\\\xe5[W\xe31\xb3\x00\x933Gw\x9cM\xaf\xd5r\xb2
b\xa9/\xe52\xe9*C\xdf\x03;\x97\xc8\xf2\xc2O\x9c\n\x7f>\x12\x06\x8aI\x15q\xb2?\xe4k\xce\x97
\xeb^\x98\x98\xb1\x91\x1a\xcc\xa8\xc2`eh\x9a\xa2\xc8ec\xd8\xf0s\xb8\xa5@\xf8Z\x1f\x97O\xa7
\xb2\x90\xbd0*\xa0\xc0t\xe4\x8e\x83\xadz\xa7#\x1eB\xe0,\x85\xccU\xcb\xb8\xe1w(b\x19@E\xc2\
xdag\xbf\xce\x8f\x04P\xadz\x92\xc0&\xd8\n\x1dn\xe9\x07s\x10\xcae\xdfq4\xd5\xf7\xb3>v\xc9E\
xc2\xebD\x1b\xf5\x8a\x13,q2\xdf\x1fE\x00f"f\xa2\xc8O\xc7B#]\x992l c\xb2 \x1fp\x84&H\xdc\xc
1\xb3\x9b\x0c}2\xc7\xb7\xd8\xc0\xa2\x97\xb9\x8ew\x87<)y\xb7\xeb\x85q\x84\x8e\xed+N\xe6\xda
g\xf39\x1c\xe9\xccTv\xa3\x8ech\xe2KY$\xcd}\x0b\\\xb3\xb6\xeaX\x18\x8d\xce\x90&mI\xc3;2\x8a
{\xa8\x03[I\xc3c},\xf2IU\x86\x87\x91\x93\xb41%\x92&\xf9\xa8\x1f\xdfW\'\x9c\x98\x12\'\xb4\r
\x9d\x8a\x94\xc9\xdd\x83\x16E\xf2\xca\xbb\xa7\xb7rY\x0e\x12\xd39\x1c\xb3\x06\'\xb3\xc0\tm\
xf0\x98]\xa8!\xef\x1c!Qh{\xaf\x10]\xe5\x13\'\x8d\xf5DG\x08\x1c\xa1\xc6\xd6\xf1_\xa1\xa1\x8
4\x1f}\xb0r\xb5\xbf\xae\xf2x\xbd\xcfs\xab\xca\x8e\x84\x00\xba\x80\x8e\xd7\x16?\xc0\xb0\xb9
R8\x01\x00\x19\xae;4\x8a\xa5\xec\xc5r\x1a\xaa\xae\xef\xcb\xe2t\x11+\x1e\xd1\xb1=c\xb0z\x0b
\x9aM\x1bn\xaf\x97\x10nBY\xe8W\x9e[Q bj\x97\x8dtKo\x14n\x02\x982\xaf^\x95\x11hp\x87\x19n\x
82FMMG\xfa\xb2\x90\x97\xaa\xd0}\xd5\x95\xe7O\xe6\xa3\x0f\x95^-\x01\xab;\x9b\x9b`\xbb\xeaB\
x80-0\xb1y\xb09\'\x92\xfb\xf9U\x98\x84Bu\x05\r\xc4$j\xda7\xfc\tH_\x8a\x83\xc7D\x15\x8c\x0c
\x95\xb1\xcd\x0f(\xde\xe5q\xdf\x94>\xa1\x10\xd2\x90\x82\xf6\x8c\xa5+}\x86Oa\x83]\x84\'O\x1
4\xa7\x96#v*\x97\xb2\xaf\n\xf9\xf6\xa8\x81\\x\xe16S\xf7\x93\xc6\tn\xb0\x85g\x02f\xbfY\xda\
x96\xc7\x93<.\x93\xbeV\xd8\xa3\x00\xfa\xcaH"}\xe6j\x9e\x87\xa0q\xafX\xceu\xb0\xed\xd9=\xa4
\xa3\x7f\xba\xa7\xad/\xfd\xfcR\x15}/\n6I\xa8\xdeI\x82\x05\x96X\x05\xa3\xb0LYR\xfb\xb6;\xe6
Lq\xc4\xde\xaa\xa5\xb5\xb5qa\xe4R\x1c\x8dt\xa4\x9f\xc5\xe9\x9e\x11\xdf\x1a\x8e\x98\x91\x01
 \xe8\x88\xa62\xcfwy\x91O\xadX\x95Ac\x1c\x04ne0\x9b\x85\xcf\xe6W\xb2\x15=X\x9dl\x15\xb3\x9
a\xc7\xa4\xab\xba\x07\x87\x86\xaa\xd0\x83\x84\xd4\x11\x0b\xa5\xcfL\x85\x13\xac\x82\xc6L\x1
0z E\xb7cn\xab"?\x95\x05\x9a\xd4\xb1\xdb\x99\xaa\x98p\x033\x1b\x8e\xbc#\x0c\xd6>\xbb\x96\x
be\xc4\x86:t)\x8b\xdd\xa9\\\x12T\x9b\xa7\xa01\x14*\x9eX\xf9\xf5\xb1[i$\x05Nxl\x84=\x19\xb3
6\xdc\xb6=\xbbc\xc0<]J\x7f\xf7v,\xd6\xa7\xd2\x9f|\x08`\x1fny\x8b\x1f\xbbq\xd2g\xb3f\xc6\xf
6G}\x17\xc4uV\xc4}}\xeczWu\xa7\xbe\xecrS\x15\x8c\xb2\xe6N\xc1\xeb\x111\xce}I\x07\xc8\xf3\x
9b\xe0kO\xde5<\xe56\xdc\xb6\x1d\xb6\xf0D\x9a\xf4\x9d:\x81\xa5\x8f\xba\xaa(\xcf\xc7\x9c\x88
\x1c%\xfb\xccc\xbb<\xd6\x92\x17\xf1E\xac\xb2[\x98@\xe9KU"\xb6I\xe7\x88\xa6\x9e\x15\r]\xad\
xcd\x11M\xf5\xb1;\xe9c!\xdf\xcan\xf2\xebO\xfa\x88\xe54\x0b\x93\x85!\x98/$\x81w\x8c4\xe1v\x
8e\x1a\x9eL\xc2\x9fl\xe5\xeb\xabX\x96\xafG\xbf\xbc\x88U;1\xa8\\\xb4\x9d_\xb1\xc5\n\'\xf0\x
9d\xf9\xa4\xe3\x88\xd59\x92E\x8ets\xec\xca;\x05\xde\x8eE\xaeK\xcc\'2\xaeJ$\xb3\xfd\xcc6\xd
cg\xd0\xc2\xea\xa1\xb1C\xf5\xa9\xc4\xd5\xef\xd2/\xef\xfd\xa7>\xff\x11\x84\xa1\xd5\xea1\xaa
\xdaJ\x0fwY\xae\x1e3\xd5\x1f[\xaaV\x0e\xd5\xddkx|\xe2!)\xbfd\xfd\xa13Cu\xfe\xd3\x9f\x87\xe
a\xcf?\xe5\x9f\xf9\xdf\xae\xab\t\x0b\x1f\xe1\x9a\xcb\xa81\x82DP\xb9\x00<\x9f\tP\x03\x1d]GS
B\xd5\x92\x0cUgOw\xa5,4\x92\xfc\x1e4B\xaf\xe5r\xf7\x0e\x94\x18\t\x83-\x01\xa9\n\xb6+\x81\x
b7\x82\n\x7f\xa7x\xb7~\xab\x8c#PmF\xfa\x99r:\xb6\xef\x14\xaen m\x1dU\xab\x81l3\x1b\xc2\x04
\xdd\x91\xca\xf5\xd4\x96\xcb\xdc\xd6|=+\xa3\xe7f\x9c\xbbp\xbb\xaa\x83\x04\xbe\x06\xcd\xa6\
xc1\xcd\xb3\n\xb6"*5\x13E\xac\xeb\x02\xc9\x92\xc7HU\xab\x9d\x93\xabi\xaa\xf9\xd3\xfd\xba3\
xd3&\x93>\xbb\xa3\n\xb7\x04\xc6#\xd7\xe4\xbeU#\x96dh\x8c\x8b\xd8\xf6j\x02y/\xb8w\x028\x81G
\xe1\xc1\x8e\xe8\xa3f\x82\xc7&$\r>\xd5\xf1)\xc9\x8a\xdc\x94\x9e]\xed\xfc\xd3\x19\xd8~\x00\
xc2%\xbb\xa5\x95UrJ&==\xe7/x\x19^\xf9\xd7\x8f\xcf\xd0\x06\xc1W\xfe@\x93\xb93_\xb3v\xf1\xb1
{\x1e\\\xf2\x1c\xdf|\x9f]\xb1\xc5_G\x01\xc2\xe0\x8a\xf9<L_\x93o\xd3\xf7\xddG0\xa5\xe74D4\x
0c\xd1f^\x0c\xf5s\xdch\xb1t\x1b\xa3K\xe6R\xf9\xd2\xd8\x88\x81\xb4\xa1K\nB\xa0\xbd\xdd\xf3\
xc0v\x07Y\x83n\xcdy\r\x98\xfb\xfc\xef\xed\x1a\x06\x96\xc2}\xa1OS\xa9\xa7\xc5\xcfE\xf2m\x8f
\xcad\xcf\x00\x1c\xa3\x8cS\x99\xbd\xcc\x92\xb8\xc3\xc1n2m\xdbf\xe4\xefs\xad\x84\xd8* \xb1T
\x99\xb7\xfezhhI%\xdd\xdc^2\x95\x9d\xc9\x91\xf8\xeb\xf5~!\xbf\xf3\xed\x94g\x0b\x18x\x92\xb
c\x16\xc9\xbc\x99\xedj\xeb\xd9\xb4\xf6\xd8F7Z\xf2\xc0\xda2G\xeb$\xd3\xeb:;\xaf\x9f\x8b\x81
\xfe@5]\x8cW\xf3\r\xc7\'Q\x1c^A\xda\xa2g\x0e\xf4,\xe4\x1b\xb0\xd4<{,\xcb}\x86\x11,\x9e\xce
\xa2\x93\x97jA\xb6\x84]\x1b\x80\x90\xe0\x86v\xe0\xc0\xe2\xddg\xa5,\x90\xcc\x0f.]\xb8\xe1\x
f9\xb5\x1a\xdb=-v\xf9n\xb1^\x17\x87i\x9d\x8d\x9b\xc5\x8d\x95(\x1a7%d\xae&\xe3L\x88\xbc\xbe
\x15&\xbb\xd2\xfc\xf4}\xf7L\x16\x99ia\xbe\xd0v\x1e6\xdf\xe7\x97=\x1c\xa3g\xc9\x1d\x8eD\x8e
~\xfc|f?\xf2\x05Z\x17I\x03]\xc4w^d^f\x86\xf4\xe1\x80~\xe4\xab\xbbx\x88\xb7\xf9e\xde"G\\\xc
d\xad\xde\x1f\x92%\x97\xd0\xa9T$\xb7\x97\x0cp\x9cF,&\xfb\xdd!I\xab\xbc\\\xff\xf4\xe0\r\xd9
\x13\nd\x9a\xcc\xf5\xfc\xf2\xc16\xca\xb3\xc8eg"\x18\xa8\x06y~\\\xb4\xff\x83\x8b\xbf\xf9\xa
7\xf4\xf9q;l\xdb_\xc6\xff\xd1\xfe\x9e\xbd_\xd8?\x8b\x85|\xd0\xfd\x7f[\xa5+5\x7f\x94(N2\xac
O\xd9\'T~z\xf8\xea\xc9\xcd\xd1\x1b\xf6\xc18\x98\xb72^o\xf6\xdeW\x9a.zQ\x9cI\x89_\xf6\xa1\x
abM\xe1\xdb\xb6\xf2-nD1{!d\xf9A\xa7\x181w\xa9\xf2\xf2\x03\xb1\xe9\xb2_\xc8e\x86\xa6}\xc6|\
xe0^x\xe6\xc9t7;\xbb\xf9y^o\xb2E\xf9\xfd0n\xd6\x1fIf\t\x9b%\xaea\t\x97\xaeC\t\xf3\x8f:y\xe
5(\xdf\xed\xceO\xdf\x85$*;3\xe3EfGj\xb8p\x11\xe6\xc1\x92\xde\x02D\xe2\xf4\xfc\xb4\xcd\xce\
xfd\x86\'\xf4\x87\x1b6\xeb\xb9V\xa9g\xad\xcd<Y\x1c\xb9\x04%\xba^\xe7A|\xf7\xfd\xbe"\xbf\nK
\x8e6\xfb\x03\x8apjuS\x9b\xf8c\x80o\xb4qu\x84\xe4b\x9f\x97\xf5\xfe\xbc[\xec\xd0<\x10>\x17H
\xaa\xe4\x16=g\xbe\xcd\x8ea\'\xb7{\x1d7\x01X\x81\xfd\xa1o "\x9b\xdd\x02\xe3\xc0\xba\xd0\xa
b\xf7\xd0\rWU\xa0\x93\xe0\x8b\x03\xf8\x19\xafE\xa6\xcb.\x1c\xe8\xb7)\xa2\x02\x03\xd7|\xc8\
x95\x11\x069\x8aO\xcdA\xb7\xa1\xff2W\xd5\xd2\xd4H"\xfe\xf3\xfc\x14\x1f\xce\xfd*\x97\xf3\xe
a\x16e/sM\x97s3}\xff\xb9\xe8\x93\xbdg\x7f\xe4\xcd\xf3~\xb6\x82{\xe0\x9a}\xd4\xa2\xa6`.=K\x
82\xcc#\xdf3\xc4\xd2\xdd\xa7\x02\xefr\xeepL\x0e\x07vM\xfd\xf1\xfa?', fin=False, rsv1=True,
 rsv2=False, rsv3=False)
new_frame extension Frame(opcode=<Opcode.TEXT: 1>, data=b'{"call_sid":["CATEST","CATEST2"]
,"segment":["/////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////w=="],["emhfW1lVVFVWWFxfZW177+3r6+/y/nv37OLb
08/S1Njd5fh2a19cWlpXV1xofuvl4ebu8/93a2xvb3BvbGdmbHz26+zm5+vo6vF7b2xpZWNhYWNma3X+9urf3t3d3t
7h5eLl5+rzfW9pZWFfXmBfXV1cV1NWXGNse+/h3NjSz8/R0tjh7XhnZV9eXl5bWlpbXF9ka/rq493X1NHOzs/S1w==
","3+t6+fa15bVg==","VFZYW19nc3708Ozo6+ro7PP+eXz///Lq5eDd3d/p9nRmYmBhY2JmbW5yen39asfdaslkdj
flksajfajdlasjflkjalfjsalkfjsljflkjflkajflkasjlsajflksajfajfklsjflksajf,w/fXz+Pt9//v37uno6
+/093x4cW9yc3JubmppaGlqbG5wcXZ8/O/r5uHf3+Dg4OLi5Oru+HRlXFtZVlhaXWFpb3708ezn5N/d3d3c3N7h4uj
s9XxsY15dXFxeZGxubmxram1zfu7f29jV09PW2dvd5fN2Zw==","XFZSUlJWWl1jbHJ89u7p5+Li5e3y+3x7fPzx6+
kk5+35cWdfX11cX2RqbnF+8+7n5eXp8fHv7+3r6Ofm5uz1fm5nZmlrbW92cm5rZmloamloZmlxaljfffffffffffff
lksajflkajflksajfldsajfksajflajfksajfdjfalksjflkajflksjflksajfkdslajfl//Ps59/d3N3c3N7f5u3w
/25lXlxbWVtdX2NmbXT/8/Dp49/d3Nva2tvc3uTt+35kX15bWlxgaGxtbGloZGNman7q4tzZ1tXW2Nvf6Q==","+Wx
fWFNSUVJXXGJpbnF99u7n397f3+Hn7PP18vTu6eXk6O7+b2llYGBhZWdpbnf47+nm5uno6Ofq7u3s6+vt7/9vaGFeX
2Jmb3d4/f56c29ubmxram54/fHp5N/e4Obl6O7y9v//dGpmX1xcXFxeYmNod/rx7efg3N3d3Nzd3Nzf5+39bF9bWVh
YWl1lanZ6e/99dW5y/u/n4NvU0tLT1g==","2t3n/WpdVlFRUVNZXmRpbnv57ujg3Nzc29zk6u7z9fTw7vX3/nFoZW
NeXFxeXl9jam968uvn5ePj5eXm5ubm5uns9HdnXFlYWVxfanX68vd7enZ1dnNycnv57ufh3NnZ3N7j6vf8fnVvbmpp
aWNgXmBiZGZsd37z6uTe3Nzb3N7e3uTo7n5qX11bWltbXF9ma25vdnt0bm55/u/l3tvX1g==","1NXY2+Hvc2JaVFJ
SVVtfZm56+/v47urj3tvc3uLr7/x++/93cm1ubGdpbGxsamppZWhobHX87ujk3+Hi4eLj6Oro6/L6dWlgXVtbW15nc
vTu7O7w7/L4/P90cHZ8+e3m393e4efxem5pZWdoaWlpamZkaGlqbG1yfPrt5+Hd3d3e4OHm6+3t+nFnY15dXV5dX2V
rbnN7/fr+e/358eji3Q==","2dbU09ba4u91ZFtVU1FRVFpeZ257//767+jk3dvZ293h6e3v83x0bWhjX19hZGdpaW
diY2JmbXb06OTf3Nzc3N3e3t/k5+z2eGtjXFxdYGNpcf307+/2fnd5d29vcXV6+evg3dzc4Op9amZkY2hpbGxpZ2Vo
aWppbW9xd/fq5N3b3d3f4ubt9ft5c2tmYV9fX19iaGttcnv68vP38u7u7w==","5+Hd2tnX19nd4+51Y1xZVVRVWVx
jbHZ4env/+vHn39zb29zg5Obp+HhtaF9cXF5mam9ubmxsaWlsd/7v5t/d29na3N3f4enx//0+P1wYVtaWVhZW1xfYm
RnaWx3e/Tt6uXm59/c29rZ2d3n7v1oZWRhZG51cnB4en7/fXNtdA==","dnd7+vb09u/p5uTj6Ojp9P90cnBoZ2RiY
WJhZ2x2/+/p6OXj3t/d29vd29zl9ntpYl1cV1JTWFpcYmpvamhpZmVnaW979ejg3NrY19XX2d7s/XVwbXJ0d3r6+PX
t6Ojm3t/h5ePq7vb3d21maWZkYV5bV1NST09RVFldXWFobHTw6N/d2dfZ19LPz87P0tbe7HJnY1xcYmhlYWdiZmx2c
g==","bGxzbnT66+zo5N/f3Nze6Oz8eXNxb2xta2lrbGZgY2ZobHjx9/fv8Ozg3t3f3N/q925mX19cV1dWV1leYmZo
aWliYWVlZ3Xx5uHZ1dTSz9LX29/t/asljflsakdjflkasjflkajfdlkajslkdjfalksjflkasjlfkajslfjalskjfl
aksjflaskjflaksjdfjdsalfkasjfdlksajfdlasjflksajflsakjflsakjflksadjflkasjfdlksajflsajflksaj
fHx3b213cXd8enb58/fv4+Dk5+fs7uvm7P57fG5samthX11cWl1dXV1dW11gZGRq+fbu59/j5+Pf4OHb3Ob7b2RfXm
Jianv5/fLu7g==","7ujq7/Hw+Pjv7fHs5OTt6/N1aWVhXlxjZGVtcXJzfnlzeuzm6OHc4N/g4eLe3eDf4Ob8Zl9bW
FlcW1dZXF1faHRvdHxxcXByen3z7eTd29rY193j5/FuXl5dW11nbG5senv89Orn4dzb3NrZ2dvb3ub0/m5lYl9bXFn
65e3hcFhNTWVnZ0tHR2hk+tps+bvNRGtdaNhNxlxDVM3G6rXAyg==","sbXH2s7NzmnATjEyRDsvNDFw229r3t3Aub
+64r3XzsxANCxIRy4xPkP617661LzEscDFelbGvLnlZ9vPdMet89+Pe7G7+6+l0RDs9RUdc+mJXXc+9vg==","wr64
t7/SWlhxZlxEQENCS1ZNS9+/u8TX7dTMzd5vUUtLTltjeuXqzcfbbOf+d3dfT0JAUe7Z7d7LwMTfTk5Y52JJSEdIXO
xVTE/40d5gWNzLztHO0tPc09LleldX4ttZV1JNTlJcTkJDWs7K1c7EurnC3FhbWUg+Pj1DX+lzbdi+t7nD09TV2931
/WBkbmdoaE5O59re+11bXn7m+U9FRw==","W1dVUvPEvsDgaujS7WRVREJJWUxJTuLEw9Z18uLZ/9vc5uz55driWnT
r7VhIRD5ETnj/VEltzsLIzMS/u8DdXv38bV1KQD9KVE1JWNe/v8XR08nMz91lUU1KVHdiY2bizMzO1v5vcXtlSUNGX
d/vfPbNwMT+X3P89F5SRUNPaVZJQ0/w1th14dPNzczMy9Lf0t1vTk5b9+asdkfjsaljflksadjflksajflksaflkds
ajfjjlkdsajfffffffffffffffffffffffflkdsajffffsalkdjfalkdsjflkdsajfffffffffffffffflafzyZ1FN
T3lhTg==","Q03r0dLY0sS4usniZFJLS0A7PEpbWk5Z3MS6vcnW2tja2t3ebWz06/9VUlP319voaVZy19xoSEdGT1x
ST92+vMXT0dPRzvtLQkJLTEZIUuLJyNTt59zd3c/Z/Gvm1N92YlNgX1VRRkBIbd5fTk9n08nR5c/Ev83X4G7w415FP
kBOTkpLXN7KvsLJzcfP0tttT0dWYXd+Z1rrzsbI22pa5g==","7V1LSU183PtlecnFys/i7evc81dESVZcSkRER1zs
5XzW1dfNw8DT2tTY6mdOSlFe4+H+SUpe/15LRE334tv60cS/vsrfW1hbXEU+QFJbTlZm6s7Cx87b3+veydHnbn1v73
heUlj62MzaaGnc1d1XQkBFUkpHVdzHw8TMzc7GzexIQEpNS0tKVeDSztbX0+rTycbc7+zZ0t54T05IT19PRA==","RVXv3F5UU9rP2ur', fin=False, rsv1=False, rsv2=False, rsv3=False)
2025-07-09 09:30:58,807 < TEXT '{"call_sid":["CATEST","CATEST2"],"segment":["//...PRA==","RVXv3F5UU9rP2ur' [4096 bytes, continued]
data b'\xc0\xfe'
new_frame Frame(opcode=<Opcode.CONT: 0>, data=b'm\x94K\x8f\xa48\x16\x85\xffKmi\t\x8c\xd3\x
01\x1e\xa9\x17\xf9\x80\x88"x8\xc1\x18\x07\xa3Z\x00\x86\x8c\x02\x07\x15\t\x86\x04K\xfd\xdfG
99=\xdd#\xcd\xe6\\\xfb\xca\x92\xf5\x9d\xe3\xeb;\x10\xe1y\xc7\'\x05\xf1Zs\xef\xe91\xf5@\x98
\r\x82\xb5\xae>nMx\xb6\xe2:\x81\xc7{L\xe5\xdd9\x9c\xd2\x9e\x1f\xc7l\x8fL\xc0}\xb5\xd6\xc5\
xd3\xf7\x94\xf5\xd6E\xb2\xa2\xc54\xdcf\x87\x81\xc6\xfcn\x03L\xa8\x8c\xd3\x94\xba\x06=N&\x9
8abG\xce\xcb\xdaP\x02\x17Z\x9b\xb7{\x9eY`\x82\x86_e9\xee\xa0\r\xa2\x8ci} /\xbf\xf4\xbc\xbe
l3\\\xf9\n5\xf7\xa4\x9fz8a\x16*\xb0\xe8\x89\x9e\xcd\x1e\xb7S\xb67\xce{\xe1\x83\xab\xbb\x80
\x89zx\xb1\xdf~\xff\xfd\xdbo\xdf,\xa3[\x85\x82\xb1\xcd\xee\xa7\xccC,\x03A\x0b#\'\xd8\x1a\x
18mn\xcd\xaa\xfc\xfa\xf2\xea\xc9$\xcd\x15\x17\t\xe4z6k\xe8:\xde\x07\xee\x85\x8di\xa2\x17\x
99\xa4\xc3\x9d1y\x8d2\x06\x1b\xdb\x06u\x99\x9c\xfa\xc3\r\xaff5\x0b9\xf4]%\x071\xf7\x9d\x1c
\xe6\xaa\xef\xc4W\xf9S\xab\xf9o\xeb\xbfD\xfc\xd5\xfd\x9f\xd3\x9f"\xe6\xffS\xfe\xb6\xa9\xe6
\xcfK\xffl\xf5\xcbK\xb2\xe3\x9a}\xfaP\xe4\xc0O\xbd-H\x07\x95\xd51\xfd\xbeE]\n\x85S\xc0B^r9
\xae\x00o\xd7"\t3=c\xab\xf0\xc5\x87{\x8c\xc3\x9c\x81\x96Y\xa8\xe4\x06I4^\xa9\x9e\xbbHc\x94
\xe5 >\xbfzO\xcf\x19\x9bV\xed\x9a\xc4\x8e\x9c\xe7u\xa6\xd9\xa1[\xe1!\x01\x84~\xf9[\x10\xa7
7d\x10\xe5\xe3\xe9\xca\x07@y\xb7B\x18O\xad\x9ey\x82N|>\xd8b\xa2\xc35\xce\x07D\x98/{Sqf\xb7
\xa1eG\xda\xd3\x8b\x10\xc5\xb1\xaf\x91\xbc\xc7\x14\xf2\x1a\xc4\x8e4\xc5\x94\x9b9\xf0\xb3AF
\xd4\xc2%\x8at\xa0\x9b\xfeesGR\r\xe0L=p\xce\x86-\xc8mZ\x83Xw\xb0q\xfc=\x82\xd4v\x9d\xb3\x8
6\x9fY\xe1{\t\x10a\x86\xe6\xf0\x08\x9cn\x05\xa8\x96[\xc9\xd5H`d\x12 \xf8\\X\xf8Ls\xe9g\xd6
\x95\xf0x:\xed\xb3\xd9\xe1\xa5n\xa0\x11_\xa8\r\x85\xfd\xf8o\xb4\x87[P?\x880y8\xde\xcb\xcb\
x1aZ\x95\xdc\x9aB\xde\x8b<G\x02\xe0\xb5\x03\x98\x90\xbdY\x13\xf7\xf8D\xb3\xa1||\xb5R\x9f-/
\xa9V$\xdb\xdcg\xfc\xa1\xba\x8fv\x81o\x8e,\x13\xb6\x86K%\x83\xe4\x92\x98\x1f\x17\xb65\x1c\
xc2\xc66\xd7\x1e\xa8\xb1w[sF\x86\xb8\x17l\xa3\xcc\xc3\r\xf7\x83\x94\x1b\xbc\x82\xc6Z\xda\x
cd\xea\xed\x8b\xff\xc6\xbbS\x89\xe4\x16\xb2qe\x962G\'\xd6\x1b\x1fp\x92y\x80\xd3\x1c4\x87x"
z\x1e\xe3}\xd6]\xe5\x07\x19\x1d@\x9a\xe7 \xcao\x0e\xb5U?9\x8ds\xde\\\x9d\xfd\x07M\xbb\x0e\
xe3\xde\xfdHm%r\x0b5n\x0c\xa5\x8d\x81~h\xef3\x93\x00\xc1\xb8g\x96\xd2\x99\xbd\xfa%\xf7Y\x9
8Z \xca@|\xd3\xae\x0e\xb5\xa1\x8d\x03\xee\x18\x04\xa8\xac\xc4X\xba\xb7\xb4\xec\x94\xd9\xd6
L1\xb1\x8cW\xd8\xddUs\x04e.\xb5\x89\x17G@u\x8a\xb6\xa8\xa7\xe8\xc8\xe2tH\x1f_{t\xca\xc7\xe
9b\xe1\xae\xd2\x11y\xdc\x95\x98Zl\xd6\xd0\xdf2~r\xf0%\xc7\xbc\xb2\xcd\xb5\x1b\xef=\xc2S\x8
5\x8ci:\xb4b\x16\xc7Q\x1f\x08n9P\xac\x00\xf77\xe6\xa1\x94\x93\xbe\x05\x18^a\xb4\x9e\xf7\xa
f\x07\x89|\xd3@bZ\x98\x85\xc4a6\xa9\x8d\xcd\xed\x90\x00\xcc\x06\\\x16,&\xcc_\xdf\x1fT\x98X
\xb3\x99\xc0QN\x05\xb8g\x85\x1fG\x99\'\xd3ZA\x8e\n\xb3\xd3.\x7f\xdc\x1bH-Q\xff\xa2V\xfaL}\
x96Q\x0b\x94\x95Z\xa9-\xcc\x06\xc1\xf8\x9d\x17\xce\x02T\x98\xda\x8a\xe6\xa8\xbd\x83*G\x11\
x1dPD\xe5}B"\x8c\x9d#z\xebD\xcf\xe0\r\xcbCLrh_oH\x99mU\xa4\x8d\x88\xc7\xd2\xedL\xb3\xb2\x0
3Z\xc8\xf4r!\xdd\xfbC\x04\xcf\x9b\x0b\tb\x8ad\x16{~\xb5\x02/3\xa6\x12\x8a\xb5\xd1_\xa9m\r\
x0faa\n\xe0\x9a]!SV\xddDS\xf8\xb1hI\xed\x1c\x04L\x81\x9a\xae\r@c\xcd\xb6\x9fM"\x9c\xdaT\xb
8,\x02\xd0\xf8\x80\xe7\xf9=s\x85\xc3\xe02\xb6\xda\x85\t2\xd7\x1d*\xb5\x17\x03\xbe\xc38L\xe
1\x899.\x14m\xc1p\xcd@\xc0\x18\xd0\xab\x8d)\xd5\x91\xf3i\xe1\xd4\x8c\xfeX\x0c \xce\xbc\xf4
\xcc\xbb\x93S\xde:e5\xe4yk`\xb6\xe3P\xe69\x0b\xa8\xf4\x0bj\xa1\xab\xa9(\xd9\x9b)\x01&\xaa\
xe9\x80\xda\xce\x8f\x93\x1c\xd6o\x86I\xfa\x92\xc5\xfdC<r\x10\xaf\xbf>\xff\x88\xee\x0b\xed"
c\xce\x8fe\x9c\xe8\xed;7\xe8\xf2\xa08\xd1\x91&\xb6X#k\t\xf3\xcd]3\x9b\xa08\x95\xc1\x99XO\x
19\x8ey\xb2\xe3\xd3\xdc\x02T\xe6R\xe44\x9f\xe4\xc7\x1c\x1e\xb5\xe0\xef\x08\x07\x15\xe9A`\x
08\xa0/\xbexk[\xe7~\xe1T\xa0\x05~_\xa6w\xfc\xa1b\x92Z\xb3\x11\xeb73+N\xad\x9e\x1db\x8b~0\x
e1\xd3[fu\xd7\x8f\x10\xbe\xe8e#\x17\x03%\xe4E=\xe77\xb3\x83\xcaL\xf5<&\x0f\xb1\x93\xc1v\x8
dW\xc7<o\x18\'T\xc6\x01\xa1\xe8Ho}\xa9U\xd88\x04\xd7\x8cmM\xea\x05\xe2\xbf\xa9\xe9\xa8\x96
\xa3\xd4\xc6FRk\xab\x8ce\x93\\\xaa\xbe\xf5\x15\xa9\xe3\xa9\x01MvX\xc3\xdd\xd17\xf1\xb3\xf5
\xd03\xb1\xd2\xa00\x1c\x0e\x16\xf69\x0b\xc9aa-#\xf5ywi\xd0X\xe8f2\xe9\x13\xabd\x0f\xf1Z\xe
3[\xbacp\xcd\xea\xc4\xb1\xb9\xe2\xe7}~6\xf4-\x98x\xbe\x1d\xb3\x1c\xddlwz\xdc\\\xa71=\x151\
xc9|28r\xaf\xed\xc3\x8e5\xd1J\xd5\xd4\xbb68v~V\xa0|\x17\x1e:g2\xf5\xb3"\xec\xf4d\xc0\x0f\x
dc\xbf\t\x0b\x1d\x89\xc6G:N\xb5\x9e\x9d\x10@pkOO\xe7\xd7/\xb4\x14\x98??\xe6\x97\xc2U:\xb1\
xed\xed\x94\x0e\xb89`\xde\xc0\xc8\t\xc1q\xda\x1a\x0f\x9d\x99\x8f\xef\xfb\x1cf\x07\xd5\x0f\
xd8\x171\x1dP\xe1\xcc0\xd8"\x1e\x0b&?\xcaa6^\x87\xb4\xdd]^\xa0\xc6\t6qm\xe9\x80\xd3\xea\x8
6\xdb\x82\xa9\x99\x0eWv\x91~V\x17\xdd\xb4MN\xa4U\xc8\x0f\x03\x8e2\x0bP,V\xa2\xa3.\xa9|\xe7
f3\xc5?\x07v\x9f\xbb\xa5\xb6W\xe5\x00|\xcer\xbcX\xd1\x1a\xd8\x8a\\Z\xb6\xd9\xc2B$\xb7\xd0E
7\xbapIo1k\xfbNe\xba\xda\xf3t\xda\xa20\xae\x064\xf1O\xb4\x1f?~\xfb\xa6~\xde\xdaYU\xb7\xfb\
xb7\x7f\xfc\x13\xda\x08\x1c\xc0o\xae\x85\xc0\x01\xff\xf8\xe3_', fin=True, rsv1=True, rsv2=False, rsv3=False)
new_frame extension Frame(opcode=<Opcode.CONT: 0>, data=b'', fin=True, rsv1=True, rsv2=False, rsv3=False)
2025-07-09 09:30:58,848 ! failing connection with code 1002
2025-07-09 09:30:58,848 = connection is CLOSING
2025-07-09 09:30:58,848 > CLOSE 1002 (protocol error) [2 bytes]
2025-07-09 09:30:58,849 x half-closing TCP connection
2025-07-09 09:30:58,850 = connection is CLOSED
2025-07-09 09:30:58,850 connection handler failed
Traceback (most recent call last):
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 1084, in read_message
    frame = await self.read_data_frame(max_size=max_size)
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy/framing.py", line 112, in read
    new_frame.check()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/frames
.py", line 320, in check
    raise exceptions.ProtocolError("reserved bits must be 0")
websockets.exceptions.ProtocolError: reserved bits must be 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/home/richard/code/websockets/tmp.py", line 12, in echo
    async for message in websocket:
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 497, in __aiter__
    yield await self.recv()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/richard/.pyenv/versions/3.9.12/lib/python3.9/site-packages/websockets/legacy
/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1002 (protocol error); no close frame received
2025-07-09 09:30:58,852 connection closed

```

**Comment by richytong** [comment]
I think the issue is on my end. I'll close this issue.

**Comment by richytong** [comment]
I am still identifying the cause of the issue. If I find out it's not on my end I will open up another issue.

**Comment by aaugustin** [comment]
OK — the problem is clear visible now.

presidium-websockets is fragmenting your message in frames of 4096 bytes. This is why you see a TEXT frame with the FIN bit unset (`fin=False`) meaning "this frame is not final", followed by a CONT ("continuation") frame.

The RSV1 bit is set in the TEXT frame, indicating that the frame is compressed. It is also set in the CONT frame, which is a mistake. Indeed, RFC 7692 specifies:

> An endpoint MUST NOT set the "Per-Message Compressed" bit of control
   frames and non-first fragments of a data message.  An endpoint
   receiving such a frame MUST _Fail the WebSocket Connection_.

Here, the second frame is a "non-first fragment" and the RSV1 bit is the "the "Per-Message Compressed" bit of control". Setting it is incorrect.

Fun fact: websockets had the same bug until someone noticed.

**Comment by aaugustin** [comment]
In case it helps, that bug was discovered and fixed in websockets: here https://github.com/python-websockets/websockets/issues/866#issuecomment-743912587

**Comment by richytong** [comment]
Bug has been patched: https://github.com/richytong/presidium-websocket/pull/6

**Comment by richytong** [comment]
Decode issue still remains, but it is not the fault of python websockets: https://github.com/websockets/ws/issues/2294
